input_target_path: "data/vkusvill_target.csv"
input_data_path: "data/vkusvill_data_without_target.csv"
input_isochrone_10_path: "data/vkusvill_isochrone_10.csv"
input_isochrone_15_path: "data/vkusvill_isochrone_15.csv"
input_isochrone_20_path: "data/vkusvill_isochrone_20.csv"
input_isochrone_25_path: "data/vkusvill_isochrone_25.csv"
input_isochrone_30_path: "data/vkusvill_isochrone_30.csv"
input_distance_path: "data/vkusvill_dist.csv"
input_highway_path: "data/vkusvill_highway.csv"
input_reestr_path: "data/vkusvill_reestrmkd.csv"
output_model_path: "models/model.pkl"
output_shap_path: "models/shap.png"
output_predict_path: "models/predict.csv"
output_map_path: "reports/result.html"
plotting_map: False